# Generated by Django 4.2.2 on 2023-06-29 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Salary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='employers.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
